resources:
- repo: self

queue:
  name: Hosted VS2017
  condition: succeeded()

steps:
- task: NuGetCommand@2
  displayName: NuGet pack
  inputs:
    command: pack
    packagesToPack: package.nuspec

- task: UpdateNugetPackageVersionsTask@1
  displayName: Updating Nuget Packages
  inputs:
    PackageFolder: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: NuGet push
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: DotNetDevOps
